import type { Gallery } from "../gallery/gallery.types";

export const THEME_CATEGORIES = [
  "All",
  "Cosmetics",
  "Portfolio",
  "Business",
  "Agency",
  "Resume",
];

export const THEMES_DATA: Gallery[] = [
  {
    id: "LUMIÈRE",
    title: "LUMIÈRE",
    description: "Luxury cosmetics brand template with teal and gold accents. Bold hero, product grid, commitment cards, and elegant typography for premium beauty brands.",
    category: "Cosmetics",
    itemCount: 7,
    createdAt: "2026-06-05",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80",
    tags: ["Luxury", "Cosmetics", "Teal", "Gold"],
    views: 2840,
  },
  {
    id: "porto-lando",
    title: "Lando",
    description: "Vibrant portfolio with a rose-to-orange gradient hero. Perfect for creative professionals showcasing work, testimonials, and newsletter sections.",
    category: "Portfolio",
    itemCount: 8,
    createdAt: "2026-04-12",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&q=80",
    tags: ["Creative", "Gradient", "Rose", "Orange"],
    views: 5120,
  },
  {
    id: "porto-florent",
    title: "Florent S.",
    description: "Dark editorial portfolio with bold orange-red accents on deep black. Ideal for photographers and visual artists seeking dramatic, high-impact presentation.",
    category: "Portfolio",
    itemCount: 8,
    createdAt: "2026-03-28",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=800&q=80",
    tags: ["Dark", "Editorial", "Bold", "Black"],
    views: 3670,
  },
  {
    id: "porto-minimal",
    title: "Minimal Folio",
    description: "Clean, typography-driven portfolio with stark black-and-white contrasts. Lets your work speak without distraction — ideal for minimalist-minded creatives.",
    category: "Portfolio",
    itemCount: 8,
    createdAt: "2026-02-14",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?auto=format&fit=crop&w=800&q=80",
    tags: ["Minimal", "Clean", "Monochrome", "Typography"],
    views: 4290,
  },
  {
    id: "biz-talentify",
    title: "Talentify",
    description: "SaaS and HR platform template with strong primary-to-violet gradients. Built for talent management, recruitment platforms, and B2B business showcases.",
    category: "Business",
    itemCount: 8,
    createdAt: "2026-01-30",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=800&q=80",
    tags: ["SaaS", "HR", "Violet", "Gradient"],
    views: 6180,
  },
  {
    id: "biz-noora",
    title: "Noora",
    description: "Light, professional business template with a neutral palette. Clean sections for features, testimonials, and pricing — suits consulting and service companies.",
    category: "Business",
    itemCount: 8,
    createdAt: "2026-01-10",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    tags: ["Professional", "Light", "Neutral", "Clean"],
    views: 4510,
  },
  {
    id: "biz-pixend",
    title: "Pixend",
    description: "Deep blue tech startup template with gradient hero and feature grids. Polished and professional for SaaS products, apps, and technology companies.",
    category: "Business",
    itemCount: 8,
    createdAt: "2025-12-20",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=800&q=80",
    tags: ["Tech", "Blue", "SaaS", "Startup"],
    views: 7240,
  },
  {
    id: "agency-portfolite",
    title: "Portfolite",
    description: "Bold, all-black creative agency template that makes a powerful statement. High-contrast design with gallery-forward layouts for ambitious creative studios.",
    category: "Agency",
    itemCount: 8,
    createdAt: "2025-12-05",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80",
    tags: ["Dark", "Agency", "Bold", "Black"],
    views: 3890,
  },
  {
    id: "agency-finito",
    title: "Finito",
    description: "Navy and deep blue agency template with a polished corporate feel. Clean feature sections and case study layouts suited for established creative agencies.",
    category: "Agency",
    itemCount: 8,
    createdAt: "2025-11-18",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    tags: ["Navy", "Corporate", "Blue", "Agency"],
    views: 5320,
  },
  {
    id: "agency-limitless",
    title: "Limitless",
    description: "Vibrant violet-to-fuchsia gradient agency template that radiates creativity. Bold, energetic design for digital studios and forward-thinking creative agencies.",
    category: "Agency",
    itemCount: 8,
    createdAt: "2025-11-01",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80",
    tags: ["Violet", "Fuchsia", "Gradient", "Creative"],
    views: 8950,
  },
  {
    id: "resume-magnetto",
    title: "Magnetto",
    description: "Striking black and amber resume template with high-contrast typography. Makes a memorable impression — ideal for senior professionals who want to stand out.",
    category: "Resume",
    itemCount: 7,
    createdAt: "2025-10-14",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80",
    tags: ["Black", "Amber", "High-Contrast", "Resume"],
    views: 3120,
  },
  {
    id: "resume-classic",
    title: "Classic CV",
    description: "Traditional, professional CV template with neutral tones and timeless layout. Structured sections present credentials with understated elegance.",
    category: "Resume",
    itemCount: 7,
    createdAt: "2025-09-22",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1604871000636-074fa5117945?auto=format&fit=crop&w=800&q=80",
    tags: ["Classic", "Neutral", "Professional", "CV"],
    views: 2480,
  },
  {
    id: "resume-vivid",
    title: "Vivid",
    description: "Emerald green resume template with a fresh, modern edge. Combines a strong personal brand with clean content sections for creative professionals.",
    category: "Resume",
    itemCount: 7,
    createdAt: "2025-09-05",
    status: "published",
    coverUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["Emerald", "Green", "Modern", "Fresh"],
    views: 4760,
  },
];
