"use client";

import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence, LayoutGroup } from "framer-motion";
import { Sparkles, Play, Trash2, Plus } from "lucide-react";
import { cn } from "@/lib/utils";

const SparklesIcon = Sparkles;
const PlayIcon     = Play;
const TrashIcon    = Trash2;
const PlusIcon     = Plus;

/* ─── Types ─────────────────────────────────────────────────── */
interface Toast {
  id: number;
  message: string;
  type: "success" | "warning" | "error" | "info";
}
interface WorkflowStepConfig {
  triggerType?: string;
  subject?: string;
  aiPrompt?: string;
  generatedBody?: string;
  value?: number;
  unit?: string;
  conditionType?: string;
  yesId?: string;
  noId?: string;
}
interface WorkflowStep {
  id: string;
  type: "trigger" | "action" | "delay" | "condition";
  label: string;
  description: string;
  config: WorkflowStepConfig;
}
interface SimLog {
  time: string;
  message: string;
  status: "info" | "success" | "warning" | "error";
}
type Branch = "main" | "yes" | "no";

/* ─── Data ──────────────────────────────────────────────────── */
const INITIAL_WORKFLOW_STEPS: WorkflowStep[] = [
  { id: "step-1", type: "trigger",   label: "Subscriber Signed Up",   description: "Triggers instantly when a user creates an account",          config: { triggerType: "signup" } },
  { id: "step-2", type: "action",    label: "Send Welcome Email",      description: "Deliver dynamic intro copy generated by Gemini AI",          config: { subject: "Welcome aboard! Let's get started ✨", aiPrompt: "Generate a warm, professional welcome email for a user who has just registered for a productivity SaaS product called 'ZenTask'." } },
  { id: "step-3", type: "delay",     label: "Wait 2 Days",             description: "Cool-down period to prevent spamming subscribers",           config: { value: 2, unit: "days" } },
  { id: "step-4", type: "condition", label: "Opened Welcome Email?",   description: "Branch automation based on subscriber engagement metrics",   config: { conditionType: "opened", yesId: "step-5-yes", noId: "step-5-no" } },
];
const INITIAL_YES_BRANCH: WorkflowStep[] = [
  { id: "step-5-yes", type: "action", label: "Send Advanced Tips",     description: "Help active users level up their platform skills",           config: { subject: "Supercharge your workflow with these pro hacks ⚡", aiPrompt: "Generate a beautiful, action-oriented follow-up email listing 3 pro tips for ZenTask." } },
];
const INITIAL_NO_BRANCH: WorkflowStep[] = [
  { id: "step-5-no",  type: "action", label: "Send Friendly Reminder", description: "Re-engage cold subscribers with ease",                       config: { subject: "Quick heads-up: We didn't want you to miss out", aiPrompt: "Write a short, engaging email re-introducing ZenTask for a subscriber who hasn't opened the welcome email yet." } },
];

async function generateWithGemini(prompt: string, _sys: string): Promise<string> {
  await new Promise<void>((r) => setTimeout(r, 2200));
  return `Subject: Your Journey Starts Here\n\nHi there,\n\nThank you for joining — we're thrilled to have you on board.\n\n[AI-generated copy based on: "${prompt.slice(0, 80)}..."]\n\nHere are a few things you can do right now:\n• Set up your first workflow\n• Invite your team members\n• Explore the AI Copilot\n\nLooking forward to helping you succeed.\n\nWarm regards,\nThe Vyntra Team`;
}

/* ─── EmailView ─────────────────────────────────────────────── */
export function EmailView() {
  const [activeTab, setActiveTab]   = useState("builder");
  const [notifications, setNotifications] = useState<Toast[]>([]);
  const [mainSteps, setMainSteps]   = useState<WorkflowStep[]>(INITIAL_WORKFLOW_STEPS);
  const [yesSteps,  setYesSteps]    = useState<WorkflowStep[]>(INITIAL_YES_BRANCH);
  const [noSteps,   setNoSteps]     = useState<WorkflowStep[]>(INITIAL_NO_BRANCH);
  const [selectedStep,     setSelectedStep]     = useState<WorkflowStep | null>(null);
  const [simulationActive, setSimulationActive] = useState(false);
  const [simStepId,  setSimStepId]  = useState<string | null>(null);
  const [simReport,  setSimReport]  = useState<SimLog[]>([]);
  const [aiPromptInput, setAiPromptInput]             = useState("");
  const [aiResponse,    setAiResponse]                = useState("");
  const [isAiGenerating, setIsAiGenerating]           = useState(false);
  const [selectedTemplateForAi, setSelectedTemplateForAi] = useState("Welcome Series");

  const notify = (message: string, type: Toast["type"] = "success") => {
    const id = Date.now();
    setNotifications((prev) => [...prev, { id, message, type }]);
    setTimeout(() => setNotifications((prev) => prev.filter((n) => n.id !== id)), 4000);
  };

  const handleUpdateStep = (stepId: string, fields: Partial<WorkflowStep>) => {
    const upd = (steps: WorkflowStep[]) => steps.map((s) => s.id === stepId ? { ...s, ...fields } : s);
    setMainSteps(upd); setYesSteps(upd); setNoSteps(upd);
    if (selectedStep?.id === stepId) setSelectedStep((prev) => prev ? { ...prev, ...fields } : prev);
    notify("Workflow configuration saved!");
  };

  const handleUpdateStepConfig = (stepId: string, key: string, value: string | number) => {
    const upd = (steps: WorkflowStep[]) => steps.map((s) => s.id === stepId ? { ...s, config: { ...s.config, [key]: value } } : s);
    setMainSteps(upd); setYesSteps(upd); setNoSteps(upd);
    if (selectedStep?.id === stepId) setSelectedStep((prev) => prev ? { ...prev, config: { ...prev.config, [key]: value } } : prev);
  };

  const handleAddStep = (
    arr: WorkflowStep[],
    set: React.Dispatch<React.SetStateAction<WorkflowStep[]>>,
    idx: number,
    type: WorkflowStep["type"],
  ) => {
    let newStep: WorkflowStep = { id: `step-${Date.now()}`, type, label: `New ${type.toUpperCase()}`, description: "Click to configure.", config: {} };
    if      (type === "action")    newStep = { ...newStep, label: "Send Automated Email",        config: { subject: "Instant update for you!", aiPrompt: "Draft an exciting marketing email." } };
    else if (type === "delay")     newStep = { ...newStep, label: "Wait 1 Day",                  config: { value: 1, unit: "days" } };
    else if (type === "condition") newStep = { ...newStep, label: "Condition: Check Clicked?",   config: { conditionType: "clicked" } };
    const updated = [...arr]; updated.splice(idx + 1, 0, newStep); set(updated);
    setSelectedStep(newStep); notify(`Added ${type} step`);
  };

  const handleRemoveStep = (stepId: string, arr: WorkflowStep[], set: React.Dispatch<React.SetStateAction<WorkflowStep[]>>) => {
    set(arr.filter((s) => s.id !== stepId));
    if (selectedStep?.id === stepId) setSelectedStep(null);
    notify("Removed step from workflow");
  };

  const runSimulation = async () => {
    if (simulationActive) return;
    setSimulationActive(true); setSimReport([]);
    const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
    const log = (message: string, status: SimLog["status"] = "info") =>
      setSimReport((prev) => [...prev, { time: new Date().toLocaleTimeString(), message, status }]);

    log("🚀 Starting simulation for: jane.doe@example.com");
    for (const step of mainSteps) {
      setSimStepId(step.id); log(`Entering step [${step.label}]`); await sleep(1500);
      if      (step.type === "trigger")   log("✅ Trigger verified.", "success");
      else if (step.type === "action")    log(`📧 Sent: "${step.config.subject ?? "No Subject"}"`, "success");
      else if (step.type === "delay")     log(`⏳ Cooling down for ${step.config.value ?? 1} ${step.config.unit ?? "days"}...`, "warning");
      else if (step.type === "condition") {
        const yes = Math.random() > 0.4;
        log(`🔍 Branch: ${yes ? "YES (Opened)" : "NO (Inactive)"}`, "warning"); await sleep(1000);
        log(yes ? "🌿 Routing to YES path." : "🍂 Routing to NO path.");
        for (const b of yes ? yesSteps : noSteps) {
          setSimStepId(b.id); log(`Entering step [${b.label}]`); await sleep(1500);
          if (b.type === "action") log(`📧 Branch Email: "${b.config.subject ?? "No Subject"}"`, "success");
        }
      }
    }
    setSimStepId(null); setSimulationActive(false);
    log("🏁 Simulation finished.", "success"); notify("Simulation complete!", "success");
  };

  const handleGenerateStepEmail = async (step: WorkflowStep) => {
    if (!step.config.aiPrompt) { notify("Provide an AI Prompt first.", "warning"); return; }
    setIsAiGenerating(true); notify("Gemini Copilot is writing your email...", "info");
    try {
      const copy = await generateWithGemini(step.config.aiPrompt, "");
      handleUpdateStepConfig(step.id, "generatedBody", copy);
      notify("Email copy compiled by Gemini!", "success");
    } catch { notify("Generation failed.", "error"); }
    finally { setIsAiGenerating(false); }
  };

  const handleGeneralAiGenerate = async () => {
    if (!aiPromptInput) { notify("Enter a prompt first.", "warning"); return; }
    setIsAiGenerating(true); notify("Consulting Gemini AI...", "info");
    try {
      const res = await generateWithGemini(`Template: ${selectedTemplateForAi}. ${aiPromptInput}`, "");
      setAiResponse(res); notify("Campaign concept generated!", "success");
    } catch { notify("Could not connect to Gemini.", "error"); }
    finally { setIsAiGenerating(false); }
  };

  return (
    <>
      {/* ── Toast notifications ──────────────────────────── */}
      <div className="fixed top-5 right-5 z-50 flex flex-col gap-2 pointer-events-none">
        <AnimatePresence>
          {notifications.map((n) => (
            <motion.div
              key={n.id}
              initial={{ opacity: 0, y: -20, scale: 0.9 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9, y: 10 }}
              className={cn(
                "p-4 rounded-xl shadow-xl border text-sm flex items-center gap-3 w-80 backdrop-blur-md pointer-events-auto",
                n.type === "success" ? "bg-success/10   border-success/30   text-success"
                : n.type === "warning" ? "bg-warning/10  border-warning/30   text-warning"
                : n.type === "error"   ? "bg-error/10    border-error/30     text-error"
                :                       "bg-primary/10   border-primary/30   text-primary",
              )}
            >
              <div className={cn(
                "w-2 h-2 rounded-full flex-shrink-0",
                n.type === "success" ? "bg-success" : n.type === "warning" ? "bg-warning" : n.type === "error" ? "bg-error" : "bg-primary",
              )} />
              <p className="flex-1 font-medium">{n.message}</p>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {/* ── Page header ──────────────────────────────────── */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="w-2 h-2 rounded-full bg-success animate-pulse" />
            <p className="text-xs text-primary font-semibold uppercase tracking-wider">
              Live Marketing Node Connected
            </p>
          </div>
          <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-foreground">
            {activeTab === "builder"   && "Automation Blueprint Canvas"}
            {activeTab === "copilot"   && "AI Copywriting Assistant"}
            {activeTab === "templates" && "Visual Email Layouts"}
          </h2>
          <p className="text-muted-foreground text-sm mt-0.5">
            {activeTab === "builder"   && "Assemble automated triggers, timed logic branches, and custom copy blocks."}
            {activeTab === "copilot"   && "Harness the elite capabilities of Gemini AI for converting copy."}
            {activeTab === "templates" && "Handcrafted design systems calibrated for perfect dark/light inbox rendering."}
          </p>
        </div>

        <div className="flex items-center gap-3">
          {/* Tab switcher */}
          <div className="flex items-center gap-1 rounded-xl border border-border bg-muted/50 p-1">
            {[
              { id: "builder",   label: "Builder"   },
              { id: "copilot",   label: "AI Copilot" },
              { id: "templates", label: "Templates"  },
            ].map((t) => (
              <button
                key={t.id}
                onClick={() => { setActiveTab(t.id); setSelectedStep(null); }}
                className={cn(
                  "px-3 py-1.5 rounded-lg text-xs font-semibold transition-all duration-150",
                  activeTab === t.id
                    ? "bg-background text-foreground shadow-sm"
                    : "text-muted-foreground hover:text-foreground",
                )}
              >
                {t.label}
              </button>
            ))}
          </div>

          {activeTab === "builder" && (
            <motion.button
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.96 }}
              onClick={runSimulation}
              disabled={simulationActive}
              className={cn(
                "flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold transition-all",
                simulationActive
                  ? "bg-muted text-muted-foreground border border-border cursor-not-allowed"
                  : "bg-gradient-to-r from-emerald-500 to-teal-600 text-white shadow-lg shadow-emerald-500/20",
              )}
            >
              <PlayIcon className="w-4 h-4" />
              <span>{simulationActive ? "Simulating…" : "Simulate"}</span>
            </motion.button>
          )}
        </div>
      </div>

      {/* ── Tab content ──────────────────────────────────── */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -12 }}
          transition={{ duration: 0.25 }}
        >
          {activeTab === "builder" && (
            <WorkflowBuilderView
              mainSteps={mainSteps}   setMainSteps={setMainSteps}
              yesSteps={yesSteps}     setYesSteps={setYesSteps}
              noSteps={noSteps}       setNoSteps={setNoSteps}
              selectedStep={selectedStep} setSelectedStep={setSelectedStep}
              handleAddStep={handleAddStep}
              handleRemoveStep={handleRemoveStep}
              handleUpdateStep={handleUpdateStep}
              handleUpdateStepConfig={handleUpdateStepConfig}
              simulationActive={simulationActive}
              simStepId={simStepId}
              simReport={simReport}
              handleGenerateStepEmail={handleGenerateStepEmail}
              isAiGenerating={isAiGenerating}
            />
          )}
          {activeTab === "copilot" && (
            <AICopilotView
              aiPromptInput={aiPromptInput}   setAiPromptInput={setAiPromptInput}
              aiResponse={aiResponse}         setAiResponse={setAiResponse}
              isAiGenerating={isAiGenerating}
              handleGeneralAiGenerate={handleGeneralAiGenerate}
              selectedTemplateForAi={selectedTemplateForAi}
              setSelectedTemplateForAi={setSelectedTemplateForAi}
            />
          )}
          {activeTab === "templates" && (
            <TemplatesLibraryView notify={notify} />
          )}
        </motion.div>
      </AnimatePresence>
    </>
  );
}

/* ─── WorkflowBuilderView ───────────────────────────────────── */
interface WBProps {
  mainSteps: WorkflowStep[];  setMainSteps: React.Dispatch<React.SetStateAction<WorkflowStep[]>>;
  yesSteps:  WorkflowStep[];  setYesSteps:  React.Dispatch<React.SetStateAction<WorkflowStep[]>>;
  noSteps:   WorkflowStep[];  setNoSteps:   React.Dispatch<React.SetStateAction<WorkflowStep[]>>;
  selectedStep: WorkflowStep | null;
  setSelectedStep: React.Dispatch<React.SetStateAction<WorkflowStep | null>>;
  handleAddStep: (a: WorkflowStep[], s: React.Dispatch<React.SetStateAction<WorkflowStep[]>>, i: number, t: WorkflowStep["type"]) => void;
  handleRemoveStep: (id: string, a: WorkflowStep[], s: React.Dispatch<React.SetStateAction<WorkflowStep[]>>) => void;
  handleUpdateStep: (id: string, f: Partial<WorkflowStep>) => void;
  handleUpdateStepConfig: (id: string, k: string, v: string | number) => void;
  simulationActive: boolean;
  simStepId: string | null;
  simReport: SimLog[];
  handleGenerateStepEmail: (step: WorkflowStep) => void;
  isAiGenerating: boolean;
}

function WorkflowBuilderView({
  mainSteps, setMainSteps, yesSteps, setYesSteps, noSteps, setNoSteps,
  selectedStep, setSelectedStep, handleAddStep, handleRemoveStep,
  handleUpdateStep, handleUpdateStepConfig, simulationActive: _sim,
  simStepId, simReport, handleGenerateStepEmail, isAiGenerating,
}: WBProps) {
  const [showAddMenuIdx, setShowAddMenuIdx] = useState<number | null>(null);
  const [addingToBranch, setAddingToBranch] = useState<Branch | null>(null);
  const consoleEndRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => { consoleEndRef.current?.scrollIntoView({ behavior: "smooth" }); }, [simReport]);

  /* Node card background — sim highlight or plain card */
  const simClass = "bg-gradient-to-r from-emerald-500/20 to-teal-500/20 !border-emerald-400 ring-4 ring-emerald-500/10 scale-105";

  /* ── Add-step dropdown ── */
  const AddMenu = ({
    show, types, onAdd,
  }: {
    show: boolean;
    types: ReadonlyArray<WorkflowStep["type"]>;
    onAdd: (t: WorkflowStep["type"]) => void;
  }) =>
    show ? (
      <div className="absolute z-20 left-1/2 -translate-x-1/2 top-8 w-44 rounded-xl bg-card border border-border p-1 shadow-2xl">
        {types.map((type) => (
          <button
            key={type}
            onClick={() => onAdd(type)}
            className="w-full text-left px-3 py-2 rounded-lg text-xs font-semibold capitalize text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
          >
            Add {type}
          </button>
        ))}
      </div>
    ) : null;

  return (
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 items-start">
      {/* ── Canvas + Console ───────────────────────────── */}
      <div className="xl:col-span-2 flex flex-col gap-4">

        {/* Tip banner */}
        <div className="p-4 rounded-xl bg-primary/5 border border-primary/10 flex items-center gap-3">
          <SparklesIcon className="w-4 h-4 text-primary flex-shrink-0" />
          <p className="text-xs text-primary/80">
            <strong>Protip:</strong> Click any block to open its properties and use Gemini AI to compose email copy.
          </p>
        </div>

        {/* Blueprint canvas */}
        <div className="rounded-2xl border border-border bg-muted/20 relative flex flex-col items-center p-6 pt-8">
          <LayoutGroup>
            {mainSteps.map((step, idx) => {
              const isSimActive = simStepId === step.id;
              const typeBadge = {
                trigger:   "bg-emerald-500/10 text-emerald-500 dark:text-emerald-400",
                action:    "bg-purple-500/10  text-purple-600  dark:text-purple-400",
                delay:     "bg-warning/10     text-warning",
                condition: "bg-primary/10     text-primary",
              }[step.type];

              return (
                <React.Fragment key={step.id}>
                  {/* ── Step node ── */}
                  <motion.div
                    layout
                    whileHover={{ scale: 1.02 }}
                    onClick={() => setSelectedStep(step)}
                    className={cn(
                      "w-full max-w-sm rounded-2xl p-5 border cursor-pointer relative transition-all",
                      isSimActive
                        ? simClass
                        : cn(
                            "bg-card border-border hover:border-primary/40",
                            selectedStep?.id === step.id && "border-primary ring-2 ring-primary/20",
                          ),
                    )}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <span className={cn("text-[10px] font-bold uppercase tracking-widest px-2.5 py-1 rounded-full", typeBadge)}>
                        {step.type}
                      </span>
                      {step.type !== "trigger" && (
                        <button
                          onClick={(e) => { e.stopPropagation(); handleRemoveStep(step.id, mainSteps, setMainSteps); }}
                          className="text-muted-foreground hover:text-error p-1 rounded-lg hover:bg-error/10 transition-colors"
                        >
                          <TrashIcon className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                    <h4 className="font-bold text-sm text-foreground">{step.label}</h4>
                    <p className="text-xs text-muted-foreground mt-1">{step.description}</p>
                    {step.config?.subject && (
                      <p className="text-xs text-primary font-medium mt-2 truncate bg-primary/5 p-1.5 rounded border border-primary/10">
                        Subject: &ldquo;{step.config.subject}&rdquo;
                      </p>
                    )}
                    {isSimActive && (
                      <span className="absolute -top-2.5 -right-2.5 flex h-5 w-5">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                        <span className="relative inline-flex rounded-full h-5 w-5 bg-emerald-500 justify-center items-center text-[10px] font-bold text-white">✓</span>
                      </span>
                    )}
                  </motion.div>

                  {/* ── Connector + add button ── */}
                  {idx < mainSteps.length - 1 && (
                    <div className="w-0.5 h-10 bg-border relative flex justify-center items-center">
                      <button
                        onClick={() => { setAddingToBranch("main"); setShowAddMenuIdx(idx); }}
                        className="absolute w-6 h-6 rounded-full bg-card border border-border flex items-center justify-center text-muted-foreground hover:bg-primary hover:border-primary hover:text-white transition-all scale-90 hover:scale-105"
                      >
                        <PlusIcon className="w-4 h-4" />
                      </button>
                      <AddMenu
                        show={showAddMenuIdx === idx && addingToBranch === "main"}
                        types={["action", "delay", "condition"]}
                        onAdd={(type) => { handleAddStep(mainSteps, setMainSteps, idx, type); setShowAddMenuIdx(null); }}
                      />
                    </div>
                  )}

                  {/* ── Condition branches ── */}
                  {step.type === "condition" && (
                    <div className="w-full flex flex-col md:flex-row gap-8 justify-center my-6">
                      {/* YES */}
                      <div className="flex-1 flex flex-col items-center">
                        <div className="text-[10px] font-bold text-emerald-500 dark:text-emerald-400 px-3 py-1 bg-emerald-500/10 border border-emerald-500/25 rounded-full mb-4">
                          YES Branch
                        </div>
                        {yesSteps.map((yStep, yIdx) => (
                          <React.Fragment key={yStep.id}>
                            <motion.div
                              layout
                              onClick={() => setSelectedStep(yStep)}
                              className={cn(
                                "w-full max-w-xs rounded-xl p-4 border cursor-pointer relative transition-all",
                                simStepId === yStep.id ? simClass
                                : cn("bg-card border-border hover:border-primary/40", selectedStep?.id === yStep.id && "border-primary"),
                              )}
                            >
                              <div className="flex justify-between items-center mb-1">
                                <span className="text-[9px] font-bold tracking-widest uppercase text-purple-600 dark:text-purple-400">{yStep.type}</span>
                                <button onClick={(e) => { e.stopPropagation(); handleRemoveStep(yStep.id, yesSteps, setYesSteps); }} className="text-muted-foreground hover:text-error p-1 rounded-lg transition-colors">
                                  <TrashIcon className="w-4 h-4" />
                                </button>
                              </div>
                              <h5 className="font-bold text-xs text-foreground">{yStep.label}</h5>
                              <p className="text-[11px] text-muted-foreground mt-1">{yStep.description}</p>
                            </motion.div>
                            {yIdx < yesSteps.length - 1 && (
                              <div className="w-0.5 h-8 bg-border relative flex justify-center items-center">
                                <button onClick={() => { setAddingToBranch("yes"); setShowAddMenuIdx(yIdx); }} className="absolute w-5 h-5 rounded-full bg-card border border-border flex items-center justify-center text-muted-foreground hover:bg-primary hover:text-white transition-colors scale-90">
                                  <PlusIcon className="w-3.5 h-3.5" />
                                </button>
                                <AddMenu
                                  show={showAddMenuIdx === yIdx && addingToBranch === "yes"}
                                  types={["action", "delay"]}
                                  onAdd={(type) => { handleAddStep(yesSteps, setYesSteps, yIdx, type); setShowAddMenuIdx(null); }}
                                />
                              </div>
                            )}
                          </React.Fragment>
                        ))}
                      </div>
                      {/* NO */}
                      <div className="flex-1 flex flex-col items-center">
                        <div className="text-[10px] font-bold text-error px-3 py-1 bg-error/10 border border-error/25 rounded-full mb-4">
                          NO Branch
                        </div>
                        {noSteps.map((nStep, nIdx) => (
                          <React.Fragment key={nStep.id}>
                            <motion.div
                              layout
                              onClick={() => setSelectedStep(nStep)}
                              className={cn(
                                "w-full max-w-xs rounded-xl p-4 border cursor-pointer relative transition-all",
                                simStepId === nStep.id ? simClass
                                : cn("bg-card border-border hover:border-primary/40", selectedStep?.id === nStep.id && "border-primary"),
                              )}
                            >
                              <div className="flex justify-between items-center mb-1">
                                <span className="text-[9px] font-bold tracking-widest uppercase text-purple-600 dark:text-purple-400">{nStep.type}</span>
                                <button onClick={(e) => { e.stopPropagation(); handleRemoveStep(nStep.id, noSteps, setNoSteps); }} className="text-muted-foreground hover:text-error p-1 rounded-lg transition-colors">
                                  <TrashIcon className="w-4 h-4" />
                                </button>
                              </div>
                              <h5 className="font-bold text-xs text-foreground">{nStep.label}</h5>
                              <p className="text-[11px] text-muted-foreground mt-1">{nStep.description}</p>
                            </motion.div>
                            {nIdx < noSteps.length - 1 && (
                              <div className="w-0.5 h-8 bg-border relative flex justify-center items-center">
                                <button onClick={() => { setAddingToBranch("no"); setShowAddMenuIdx(nIdx); }} className="absolute w-5 h-5 rounded-full bg-card border border-border flex items-center justify-center text-muted-foreground hover:bg-primary hover:text-white transition-colors scale-90">
                                  <PlusIcon className="w-3.5 h-3.5" />
                                </button>
                                <AddMenu
                                  show={showAddMenuIdx === nIdx && addingToBranch === "no"}
                                  types={["action", "delay"]}
                                  onAdd={(type) => { handleAddStep(noSteps, setNoSteps, nIdx, type); setShowAddMenuIdx(null); }}
                                />
                              </div>
                            )}
                          </React.Fragment>
                        ))}
                      </div>
                    </div>
                  )}
                </React.Fragment>
              );
            })}
          </LayoutGroup>
        </div>

        {/* ── Simulator console ── */}
        <div className="rounded-2xl border border-border bg-card p-5">
          <div className="flex items-center justify-between mb-3 pb-3 border-b border-border">
            <h4 className="text-sm font-semibold text-foreground flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-success" />
              Campaign Simulator Log
            </h4>
            <span className="text-[10px] text-muted-foreground font-semibold uppercase tracking-widest">Live Feed</span>
          </div>
          <div className="h-44 overflow-y-auto bg-background rounded-xl p-4 font-mono text-xs space-y-2 border border-border">
            {simReport.length === 0 ? (
              <p className="text-muted-foreground italic text-center py-10">
                Click &ldquo;Simulate&rdquo; to watch the automation run.
              </p>
            ) : (
              simReport.map((log, i) => (
                <div key={i} className="flex gap-2">
                  <span className="text-primary select-none">[{log.time}]</span>
                  <span className={
                    log.status === "success" ? "text-success font-medium"
                    : log.status === "warning" ? "text-warning font-medium"
                    : "text-foreground/80"
                  }>
                    {log.message}
                  </span>
                </div>
              ))
            )}
            <div ref={consoleEndRef} />
          </div>
        </div>
      </div>

      {/* ── Properties side panel ──────────────────────── */}
      <div className="flex flex-col gap-6 self-start">
        <AnimatePresence mode="wait">
          {selectedStep ? (
            <motion.div
              key="props"
              initial={{ opacity: 0, x: 24 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 24 }}
              className="rounded-2xl border border-border bg-card p-6 shadow-sm flex flex-col gap-5"
            >
              {/* Header */}
              <div className="flex items-center justify-between pb-4 border-b border-border">
                <div>
                  <span className="text-[10px] font-bold text-primary tracking-wider uppercase">Properties</span>
                  <h3 className="font-bold text-base text-foreground mt-0.5">{selectedStep.label}</h3>
                </div>
                <button
                  onClick={() => setSelectedStep(null)}
                  className="text-xs font-semibold px-2.5 py-1.5 rounded-lg bg-muted text-muted-foreground hover:text-foreground transition-colors"
                >
                  Close
                </button>
              </div>

              {/* Fields */}
              <div className="space-y-4">
                <div>
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Display Name</label>
                  <input
                    type="text"
                    value={selectedStep.label}
                    onChange={(e) => handleUpdateStep(selectedStep.id, { label: e.target.value })}
                    className="w-full rounded-xl bg-muted/50 border border-border px-4 py-2.5 text-sm font-semibold text-foreground focus:outline-none focus:border-primary transition-colors"
                  />
                </div>
                <div>
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Description</label>
                  <textarea
                    rows={2}
                    value={selectedStep.description}
                    onChange={(e) => handleUpdateStep(selectedStep.id, { description: e.target.value })}
                    className="w-full rounded-xl bg-muted/50 border border-border px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-primary transition-colors resize-none"
                  />
                </div>

                {selectedStep.type === "delay" && (
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Duration</label>
                      <input
                        type="number"
                        value={selectedStep.config.value ?? 1}
                        onChange={(e) => handleUpdateStepConfig(selectedStep.id, "value", parseInt(e.target.value))}
                        className="w-full rounded-xl bg-muted/50 border border-border px-4 py-2.5 text-sm font-semibold text-foreground focus:outline-none focus:border-primary transition-colors"
                      />
                    </div>
                    <div>
                      <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Interval</label>
                      <select
                        value={selectedStep.config.unit ?? "days"}
                        onChange={(e) => handleUpdateStepConfig(selectedStep.id, "unit", e.target.value)}
                        className="w-full rounded-xl bg-muted/50 border border-border px-4 py-2.5 text-sm font-semibold text-foreground focus:outline-none focus:border-primary transition-colors"
                      >
                        <option value="hours">Hours</option>
                        <option value="days">Days</option>
                        <option value="weeks">Weeks</option>
                      </select>
                    </div>
                  </div>
                )}

                {selectedStep.type === "action" && (
                  <div className="space-y-4 pt-2 border-t border-border">
                    <div>
                      <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Subject Line</label>
                      <input
                        type="text"
                        value={selectedStep.config.subject ?? ""}
                        onChange={(e) => handleUpdateStepConfig(selectedStep.id, "subject", e.target.value)}
                        placeholder="Subject Line"
                        className="w-full rounded-xl bg-muted/50 border border-border px-4 py-2.5 text-sm font-semibold text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:border-primary transition-colors"
                      />
                    </div>

                    {/* Gemini copilot block */}
                    <div className="p-4 rounded-xl bg-purple-500/5 border border-purple-500/15 space-y-3">
                      <div className="flex items-center gap-2">
                        <SparklesIcon className="w-4 h-4 text-purple-500 dark:text-purple-400" />
                        <span className="text-xs font-bold text-purple-600 dark:text-purple-400 uppercase tracking-widest">Gemini Copilot</span>
                      </div>
                      <p className="text-[11px] text-muted-foreground">
                        Describe what should be in the email, and our Gemini agent will generate an optimized, persuasive copy block.
                      </p>
                      <textarea
                        rows={4}
                        placeholder="Tell Gemini who you're targeting, the core offer, and the tone…"
                        value={selectedStep.config.aiPrompt ?? ""}
                        onChange={(e) => handleUpdateStepConfig(selectedStep.id, "aiPrompt", e.target.value)}
                        className="w-full rounded-xl bg-background border border-border p-3 text-xs text-foreground placeholder:text-muted-foreground/40 focus:outline-none focus:border-purple-500 transition-colors resize-none"
                      />
                      <button
                        onClick={() => handleGenerateStepEmail(selectedStep)}
                        disabled={isAiGenerating}
                        className="w-full py-2.5 bg-gradient-to-r from-purple-600 to-primary text-white text-xs font-bold rounded-xl hover:shadow-lg hover:shadow-primary/20 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                      >
                        {isAiGenerating
                          ? <><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /><span>Compiling…</span></>
                          : <><SparklesIcon className="w-4 h-4" /><span>Write Email with Gemini</span></>
                        }
                      </button>
                    </div>

                    {selectedStep.config.generatedBody && (
                      <div>
                        <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Compiled Email</span>
                        <div className="max-h-56 overflow-y-auto bg-background border border-border p-4 rounded-xl text-xs font-mono text-foreground/80 leading-relaxed whitespace-pre-wrap">
                          {selectedStep.config.generatedBody}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="empty"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center text-center p-8 rounded-2xl border border-dashed border-border bg-muted/20"
            >
              <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center mb-4">
                <svg className="w-6 h-6 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" />
                </svg>
              </div>
              <h4 className="font-bold text-sm text-foreground">No node selected</h4>
              <p className="text-xs text-muted-foreground max-w-[200px] mt-1">
                Select any workflow block on the canvas to configure parameters and prompt the AI writer.
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

/* ─── AICopilotView ─────────────────────────────────────────── */
interface ACProps {
  aiPromptInput: string;         setAiPromptInput: React.Dispatch<React.SetStateAction<string>>;
  aiResponse: string;            setAiResponse: React.Dispatch<React.SetStateAction<string>>;
  isAiGenerating: boolean;
  handleGeneralAiGenerate: () => void;
  selectedTemplateForAi: string; setSelectedTemplateForAi: React.Dispatch<React.SetStateAction<string>>;
}
function AICopilotView({
  aiPromptInput, setAiPromptInput, aiResponse,
  isAiGenerating, handleGeneralAiGenerate,
  selectedTemplateForAi, setSelectedTemplateForAi,
}: ACProps) {
  const mockTemplates = ["Welcome Series", "Cart Abandonment Recovery", "Product Pitch", "Re-engagement Sequence", "Weekly Newsletter"];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
      {/* Input panel */}
      <div className="lg:col-span-2 rounded-2xl border border-border bg-card p-6 flex flex-col justify-between">
        <div className="space-y-5">
          <div className="flex items-center gap-2">
            <SparklesIcon className="w-5 h-5 text-purple-500 dark:text-purple-400" />
            <h3 className="font-bold text-lg text-foreground">AI Copywriter Engine</h3>
          </div>
          <p className="text-xs text-muted-foreground leading-relaxed">
            Craft full-funnel email campaigns, landing pages, or broadcast emails utilizing state-of-the-art semantic structures.
          </p>

          <div>
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Campaign Flow Context</label>
            <div className="grid grid-cols-2 gap-2">
              {mockTemplates.map((tpl) => (
                <button
                  key={tpl}
                  onClick={() => setSelectedTemplateForAi(tpl)}
                  className={cn(
                    "px-3 py-2 rounded-xl text-xs font-semibold text-left border transition-all",
                    selectedTemplateForAi === tpl
                      ? "bg-purple-500/10 border-purple-500/50 text-purple-600 dark:text-purple-400"
                      : "bg-muted/30 border-border text-muted-foreground hover:border-border hover:text-foreground",
                  )}
                >
                  {tpl}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Instructions for Gemini</label>
            <textarea
              rows={6}
              placeholder="E.g., Write a 3-part sequence encouraging trial users to upgrade…"
              value={aiPromptInput}
              onChange={(e) => setAiPromptInput(e.target.value)}
              className="w-full rounded-2xl bg-muted/50 border border-border p-4 text-xs text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:border-primary transition-colors resize-none"
            />
          </div>
        </div>

        <button
          onClick={handleGeneralAiGenerate}
          disabled={isAiGenerating}
          className="w-full mt-6 py-3.5 bg-gradient-to-r from-purple-600 via-primary to-pink-500 text-white font-bold rounded-xl hover:shadow-lg hover:shadow-primary/25 transition-all flex items-center justify-center gap-2 disabled:opacity-55"
        >
          {isAiGenerating
            ? <><span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /><span>Composing…</span></>
            : <><SparklesIcon className="w-5 h-5" /><span>Compose Campaign Copy</span></>
          }
        </button>
      </div>

      {/* Output panel */}
      <div className="lg:col-span-3 rounded-2xl border border-border bg-card p-6 flex flex-col min-h-[500px]">
        <div className="flex items-center justify-between pb-4 mb-4 border-b border-border">
          <div>
            <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">Generative Output</span>
            <h3 className="font-bold text-base text-foreground mt-0.5">Gemini Response Terminal</h3>
          </div>
          {aiResponse && (
            <button
              onClick={() => navigator.clipboard?.writeText?.(aiResponse)}
              className="text-xs font-semibold px-3 py-1.5 rounded-lg bg-muted text-muted-foreground hover:text-foreground transition-colors"
            >
              Copy Text
            </button>
          )}
        </div>
        {!aiResponse ? (
          <div className="flex-1 flex flex-col items-center justify-center text-center gap-3">
            <div className="w-14 h-14 rounded-full bg-muted flex items-center justify-center text-2xl border border-border">⚡</div>
            <h4 className="font-bold text-sm text-foreground">No output yet</h4>
            <p className="text-xs text-muted-foreground max-w-xs">
              Configure your copywriting rules on the left and click &lsquo;Compose Campaign Copy&rsquo; to trigger the AI engine.
            </p>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto text-sm text-foreground/80 leading-relaxed font-mono whitespace-pre-wrap">
            {aiResponse}
          </div>
        )}
      </div>
    </div>
  );
}

/* ─── TemplatesLibraryView ──────────────────────────────────── */
function TemplatesLibraryView({ notify }: { notify: (msg: string, type?: Toast["type"]) => void }) {
  const layouts = [
    { name: "Elegant Welcome",          category: "Onboarding",    imgBg: "from-pink-500 to-primary",      rate: "71% avg open" },
    { name: "SaaS Dashboard Pitch",     category: "Conversion",    imgBg: "from-blue-600 to-emerald-500",  rate: "64% avg open" },
    { name: "Abandoned Recovery",       category: "Transactional", imgBg: "from-purple-600 to-pink-500",   rate: "82% avg open" },
    { name: "Interactive Event Invite", category: "Events",        imgBg: "from-amber-500 to-orange-500",  rate: "59% avg open" },
    { name: "Community Feedback Block", category: "Nurture",       imgBg: "from-teal-400 to-primary",      rate: "74% avg open" },
    { name: "System Outage Notice",     category: "Alerts",        imgBg: "from-rose-600 to-amber-500",    rate: "92% avg open" },
  ];

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      {layouts.map((layout, i) => (
        <motion.div
          key={i}
          whileHover={{ y: -4 }}
          className="rounded-2xl border border-border bg-card overflow-hidden flex flex-col h-80 hover:border-primary/30 hover:shadow-glass transition-all duration-200"
        >
          {/* Thumbnail */}
          <div className={cn("h-1/2 bg-gradient-to-tr p-5 flex flex-col justify-between", layout.imgBg)}>
            <span className="text-[10px] font-bold bg-black/30 backdrop-blur-md text-white border border-white/20 px-2 py-0.5 rounded-full w-max">
              {layout.category}
            </span>
            <div className="bg-white/10 backdrop-blur-md rounded-lg p-3 border border-white/10 space-y-1.5">
              <div className="w-1/3 h-1.5 rounded bg-white/40" />
              <div className="w-full h-1.5 rounded bg-white/20" />
              <div className="w-4/5 h-1.5 rounded bg-white/20" />
            </div>
          </div>
          {/* Details */}
          <div className="p-5 flex-1 flex flex-col justify-between">
            <div>
              <div className="flex justify-between items-center">
                <h4 className="font-bold text-sm text-foreground">{layout.name}</h4>
                <span className="text-[11px] font-bold text-success">{layout.rate}</span>
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                Perfect for driving engagement with highly curated aesthetic patterns.
              </p>
            </div>
            <button
              onClick={() => notify(`Loaded "${layout.name}" layout context`)}
              className="w-full py-2 bg-primary/10 border border-primary/20 text-primary text-xs font-bold rounded-xl hover:bg-primary/20 transition-all"
            >
              Configure Template Layout
            </button>
          </div>
        </motion.div>
      ))}
    </div>
  );
}
