import type { CmsForm } from "./forms.types";

export const INITIAL_FORMS: CmsForm[] = [
  {
    id: "form_contact",
    name: "Contact Us",
    description: "General enquiries from the website contact page.",
    slug: "contact-us",
    status: "Published",
    responses: 132,
    captchaEnabled: false,
    createdAt: "2026-04-02T10:00:00.000Z",
    updatedAt: "2026-05-28T09:30:00.000Z",
    fields: [
      {
        id: "f1",
        type: "short_text",
        label: "Full name",
        placeholder: "Jane Doe",
        required: true,
        options: [],
      },
      {
        id: "f2",
        type: "email",
        label: "Email address",
        placeholder: "jane@example.com",
        required: true,
        options: [],
      },
      {
        id: "f3",
        type: "dropdown",
        label: "Topic",
        required: true,
        options: ["Sales", "Support", "Partnership", "Other"],
      },
      {
        id: "f4",
        type: "long_text",
        label: "How can we help?",
        placeholder: "Tell us a little about your request…",
        required: true,
        options: [],
      },
    ],
  },
  {
    id: "form_feedback",
    name: "Customer Feedback",
    description: "Post-purchase satisfaction survey.",
    slug: "customer-feedback",
    status: "Published",
    responses: 87,
    captchaEnabled: false,
    createdAt: "2026-04-18T14:00:00.000Z",
    updatedAt: "2026-06-01T11:15:00.000Z",
    fields: [
      {
        id: "f1",
        type: "rating",
        label: "How satisfied are you with your purchase?",
        required: true,
        options: [],
      },
      {
        id: "f2",
        type: "multiple_choice",
        label: "Would you recommend us to a friend?",
        required: true,
        options: ["Definitely", "Maybe", "Not really"],
      },
      {
        id: "f3",
        type: "long_text",
        label: "Anything we could improve?",
        required: false,
        options: [],
      },
    ],
  },
  {
    id: "form_job",
    name: "Job Application",
    description: "Application form for open engineering roles.",
    slug: "job-application",
    status: "Draft",
    responses: 0,
    captchaEnabled: false,
    createdAt: "2026-05-20T08:00:00.000Z",
    updatedAt: "2026-05-22T16:45:00.000Z",
    fields: [
      {
        id: "f1",
        type: "short_text",
        label: "Full name",
        required: true,
        options: [],
      },
      {
        id: "f2",
        type: "email",
        label: "Email address",
        required: true,
        options: [],
      },
      {
        id: "f3",
        type: "file",
        label: "Resume / CV",
        helpText: "PDF only, max 5 MB.",
        required: true,
        options: [],
      },
      {
        id: "f4",
        type: "date",
        label: "Earliest start date",
        required: false,
        options: [],
      },
    ],
  },
  {
    id: "form_rsvp",
    name: "Event RSVP — Spring Meetup",
    description: "Registration for the spring community meetup.",
    slug: "event-rsvp-spring",
    status: "Closed",
    responses: 245,
    captchaEnabled: false,
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-04-10T18:00:00.000Z",
    fields: [
      {
        id: "f1",
        type: "short_text",
        label: "Full name",
        required: true,
        options: [],
      },
      {
        id: "f2",
        type: "checkboxes",
        label: "Which sessions will you attend?",
        required: true,
        options: ["Morning keynote", "Workshops", "Networking dinner"],
      },
      {
        id: "f3",
        type: "number",
        label: "Number of guests",
        placeholder: "0",
        required: false,
        options: [],
      },
    ],
  },
];
