import type { WorkflowStep } from "./types";

export const INITIAL_WORKFLOW_STEPS: WorkflowStep[] = [
  { id: "step-1", type: "trigger",   label: "Subscriber Signed Up",   description: "Triggers instantly when a user creates an account",        config: { triggerType: "signup" } },
  { id: "step-2", type: "action",    label: "Send Welcome Email",      description: "Deliver dynamic intro copy generated by Gemini AI",        config: { subject: "Welcome aboard! Let's get started ✨", aiPrompt: "Generate a warm, professional welcome email for a user who has just registered for a productivity SaaS product called 'ZenTask'." } },
  { id: "step-3", type: "delay",     label: "Wait 2 Days",             description: "Cool-down period to prevent spamming subscribers",         config: { value: 2, unit: "days" } },
  { id: "step-4", type: "condition", label: "Opened Welcome Email?",   description: "Branch automation based on subscriber engagement metrics", config: { conditionType: "opened", yesId: "step-5-yes", noId: "step-5-no" } },
];

export const INITIAL_YES_BRANCH: WorkflowStep[] = [
  { id: "step-5-yes", type: "action", label: "Send Advanced Tips",     description: "Help active users level up their platform skills", config: { subject: "Supercharge your workflow with these pro hacks ⚡", aiPrompt: "Generate a beautiful, action-oriented follow-up email listing 3 pro tips for ZenTask." } },
];

export const INITIAL_NO_BRANCH: WorkflowStep[] = [
  { id: "step-5-no",  type: "action", label: "Send Friendly Reminder", description: "Re-engage cold subscribers with ease",            config: { subject: "Quick heads-up: We didn't want you to miss out", aiPrompt: "Write a short, engaging email re-introducing ZenTask for a subscriber who hasn't opened the welcome email yet." } },
];

export async function generateWithGemini(prompt: string, _sys: string): Promise<string> {
  await new Promise<void>((r) => setTimeout(r, 2200));
  return `Subject: Your Journey Starts Here\n\nHi there,\n\nThank you for joining — we're thrilled to have you on board.\n\n[AI-generated copy based on: "${prompt.slice(0, 80)}..."]\n\nHere are a few things you can do right now:\n• Set up your first workflow\n• Invite your team members\n• Explore the AI Copilot\n\nLooking forward to helping you succeed.\n\nWarm regards,\nThe ERVFlow Team`;
}
