import type {
  StoreProduct,
  StoreOrder,
  StoreCustomer,
  StoreCoupon,
  InventoryItem,
  StoreCategory,
  AutomationRule,
  CustomerReward,
  CustomerCredit,
  RevenueDataPoint,
} from "./store.types";
import type { StatCardData } from "@/types";

// ─── Stats (uses existing StatCard component) ─────────────────────────────────

export const STORE_STATS: StatCardData[] = [
  {
    id: "revenue",
    title: "Total Revenue",
    value: 48290,
    change: 12.4,
    changeLabel: "vs last month",
    icon: "DollarSign",
    color: "success",
    prefix: "$",
    sparklineData: [22000, 28400, 31200, 36800, 33600, 41200, 48290],
  },
  {
    id: "orders",
    title: "Total Orders",
    value: 1284,
    change: 8.1,
    changeLabel: "vs last month",
    icon: "ShoppingBag",
    color: "brand",
    sparklineData: [380, 412, 438, 501, 467, 548, 612],
  },
  {
    id: "customers",
    title: "Customers",
    value: 3492,
    change: 5.3,
    changeLabel: "vs last month",
    icon: "Users2",
    color: "purple",
  },
  {
    id: "products",
    title: "Active Products",
    value: 247,
    change: 3.0,
    changeLabel: "3 new",
    icon: "BarChart3",
    color: "warning",
  },
  {
    id: "aov",
    title: "Avg. Order Value",
    value: 37.6,
    change: -2.1,
    changeLabel: "vs last month",
    icon: "TrendingUp",
    color: "info",
    prefix: "$",
  },
  {
    id: "refunds",
    title: "Refund Rate",
    value: "2.8%",
    change: -0.4,
    changeLabel: "vs last month",
    icon: "CreditCard",
    color: "error",
  },
];

// ─── Revenue Chart ────────────────────────────────────────────────────────────

export const STORE_REVENUE_DATA: RevenueDataPoint[] = [
  { month: "Jan", revenue: 28400, orders: 412, refunds: 820 },
  { month: "Feb", revenue: 31200, orders: 438, refunds: 760 },
  { month: "Mar", revenue: 36800, orders: 501, refunds: 940 },
  { month: "Apr", revenue: 33600, orders: 467, refunds: 880 },
  { month: "May", revenue: 41200, orders: 548, refunds: 1020 },
  { month: "Jun", revenue: 48290, orders: 612, refunds: 1350 },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const SAMPLE_PRODUCTS: StoreProduct[] = [
  {
    id: "p1",
    name: "Premium SaaS Dashboard Template",
    slug: "premium-saas-dashboard-template",
    sku: "TMPL-001",
    type: "digital",
    status: "active",
    shortDescription: "A fully responsive admin dashboard built with Next.js & Tailwind CSS.",
    price: 49.0,
    compareAtPrice: 79.0,
    costPrice: 0,
    featuredImage: "https://placehold.co/60x60/d14c23/fff?text=DS",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat1"],
    tags: ["nextjs", "dashboard", "tailwind", "template"],
    brand: "ERVFlow",
    totalSales: 342,
    rating: 4.8,
    reviewCount: 87,
    createdAt: "2025-01-15",
    updatedAt: "2026-05-20",
  },
  {
    id: "p2",
    name: "Business Plan - Monthly",
    slug: "business-plan-monthly",
    sku: "SUB-BIZ-M",
    type: "subscription",
    status: "active",
    shortDescription: "Full ERVFlow access with 5 seats, analytics, and priority support.",
    price: 79.0,
    costPrice: 12,
    featuredImage: "https://placehold.co/60x60/7c3aed/fff?text=BP",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat2"],
    tags: ["subscription", "saas", "monthly"],
    brand: "ERVFlow",
    totalSales: 1248,
    rating: 4.7,
    reviewCount: 213,
    createdAt: "2024-09-01",
    updatedAt: "2026-05-10",
  },
  {
    id: "p3",
    name: "UI Component Bundle",
    slug: "ui-component-bundle",
    sku: "BNDL-UI-01",
    type: "bundle",
    status: "active",
    shortDescription: "50+ premium UI components for React + Tailwind CSS.",
    price: 129.0,
    compareAtPrice: 199.0,
    costPrice: 0,
    featuredImage: "https://placehold.co/60x60/0891b2/fff?text=UI",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat1"],
    tags: ["ui", "react", "components", "bundle"],
    brand: "ERVFlow",
    totalSales: 89,
    rating: 4.9,
    reviewCount: 34,
    createdAt: "2025-03-10",
    updatedAt: "2026-04-15",
  },
  {
    id: "p4",
    name: "SEO Audit Checklist PDF",
    slug: "seo-audit-checklist-pdf",
    sku: "DL-SEO-001",
    type: "downloadable",
    status: "active",
    shortDescription: "A 120-point SEO audit checklist for agencies and freelancers.",
    price: 19.0,
    costPrice: 0,
    featuredImage: "https://placehold.co/60x60/d97706/fff?text=SE",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat3"],
    tags: ["seo", "checklist", "pdf", "digital"],
    brand: "ERVFlow",
    totalSales: 567,
    rating: 4.6,
    reviewCount: 145,
    createdAt: "2024-11-20",
    updatedAt: "2026-02-14",
  },
  {
    id: "p5",
    name: "Pro T-Shirt (Branded)",
    slug: "pro-t-shirt-branded",
    sku: "MERCH-TS-001",
    type: "variable",
    status: "active",
    shortDescription: "Soft cotton t-shirt with ERVFlow branding. Available in S–XXL.",
    price: 29.0,
    compareAtPrice: 39.0,
    costPrice: 8.5,
    featuredImage: "https://placehold.co/60x60/16a34a/fff?text=TS",
    stockStatus: "low_stock",
    stock: 14,
    lowStockThreshold: 20,
    categoryIds: ["cat4"],
    tags: ["merch", "apparel", "branded"],
    brand: "ERVFlow",
    totalSales: 203,
    rating: 4.3,
    reviewCount: 56,
    createdAt: "2025-02-01",
    updatedAt: "2026-05-22",
  },
  {
    id: "p6",
    name: "1-on-1 Consulting Session",
    slug: "1-on-1-consulting-session",
    sku: "SVC-CONSULT-01",
    type: "service",
    status: "active",
    shortDescription: "60-minute Zoom strategy session with our team.",
    price: 199.0,
    costPrice: 30,
    featuredImage: "https://placehold.co/60x60/db2777/fff?text=CS",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat5"],
    tags: ["consulting", "service", "strategy"],
    brand: "ERVFlow",
    totalSales: 78,
    rating: 5.0,
    reviewCount: 22,
    createdAt: "2025-04-12",
    updatedAt: "2026-05-20",
  },
  {
    id: "p7",
    name: "ERVFlow Gift Card",
    slug: "ervflow-gift-card",
    sku: "GC-ERV-001",
    type: "gift_card",
    status: "active",
    shortDescription: "Send the perfect gift. Redeemable on any ERVFlow product.",
    price: 50.0,
    costPrice: 0,
    featuredImage: "https://placehold.co/60x60/6366f1/fff?text=GC",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat5"],
    tags: ["gift", "card", "voucher"],
    brand: "ERVFlow",
    totalSales: 134,
    rating: 4.9,
    reviewCount: 41,
    createdAt: "2025-01-01",
    updatedAt: "2026-01-01",
  },
  {
    id: "p8",
    name: "Landing Page Starter Kit",
    slug: "landing-page-starter-kit",
    sku: "TMPL-LP-001",
    type: "digital",
    status: "draft",
    shortDescription: "10 landing page templates with conversion-optimized layouts.",
    price: 39.0,
    costPrice: 0,
    featuredImage: "https://placehold.co/60x60/64748b/fff?text=LP",
    stockStatus: "in_stock",
    stock: 9999,
    lowStockThreshold: 0,
    categoryIds: ["cat1"],
    tags: ["landing-page", "template", "conversion"],
    brand: "ERVFlow",
    totalSales: 0,
    rating: 0,
    reviewCount: 0,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
];

// ─── Orders ───────────────────────────────────────────────────────────────────

export const SAMPLE_ORDERS: StoreOrder[] = [
  {
    id: "o1",
    orderNumber: "#ORD-10042",
    customerId: "cu1",
    customerName: "Sarah Mitchell",
    customerEmail: "sarah@example.com",
    status: "delivered",
    paymentStatus: "paid",
    items: [{ id: "oi1", productId: "p1", productName: "Premium SaaS Dashboard Template", sku: "TMPL-001", quantity: 1, unitPrice: 49, totalPrice: 49, imageUrl: "https://placehold.co/40x40/d14c23/fff?text=DS" }],
    subtotal: 49,
    discount: 0,
    shipping: 0,
    tax: 4.41,
    total: 53.41,
    currencyCode: "USD",
    createdAt: "2026-05-28",
    updatedAt: "2026-05-30",
    paidAt: "2026-05-28",
    deliveredAt: "2026-05-30",
  },
  {
    id: "o2",
    orderNumber: "#ORD-10041",
    customerId: "cu2",
    customerName: "James Torres",
    customerEmail: "james@example.com",
    status: "shipped",
    paymentStatus: "paid",
    items: [{ id: "oi2", productId: "p5", productName: "Pro T-Shirt (Branded)", sku: "MERCH-TS-001", quantity: 2, unitPrice: 29, totalPrice: 58, imageUrl: "https://placehold.co/40x40/16a34a/fff?text=TS" }],
    subtotal: 58,
    discount: 5.8,
    shipping: 4.99,
    tax: 5.14,
    total: 62.33,
    currencyCode: "USD",
    couponCode: "WELCOME10",
    trackingNumber: "1Z999AA10123456784",
    shippingMethod: "UPS Ground",
    createdAt: "2026-05-27",
    updatedAt: "2026-05-29",
    paidAt: "2026-05-27",
    shippedAt: "2026-05-29",
  },
  {
    id: "o3",
    orderNumber: "#ORD-10040",
    customerId: "cu3",
    customerName: "Priya Nair",
    customerEmail: "priya@example.com",
    status: "processing",
    paymentStatus: "paid",
    items: [
      { id: "oi3", productId: "p2", productName: "Business Plan - Monthly", sku: "SUB-BIZ-M", quantity: 1, unitPrice: 79, totalPrice: 79 },
    ],
    subtotal: 79,
    discount: 0,
    shipping: 0,
    tax: 7.11,
    total: 86.11,
    currencyCode: "USD",
    createdAt: "2026-05-26",
    updatedAt: "2026-05-26",
    paidAt: "2026-05-26",
  },
  {
    id: "o4",
    orderNumber: "#ORD-10039",
    customerId: "cu4",
    customerName: "Liam Chen",
    customerEmail: "liam@example.com",
    status: "pending",
    paymentStatus: "pending",
    items: [{ id: "oi4", productId: "p3", productName: "UI Component Bundle", sku: "BNDL-UI-01", quantity: 1, unitPrice: 129, totalPrice: 129 }],
    subtotal: 129,
    discount: 0,
    shipping: 0,
    tax: 11.61,
    total: 140.61,
    currencyCode: "USD",
    createdAt: "2026-05-25",
    updatedAt: "2026-05-25",
  },
  {
    id: "o5",
    orderNumber: "#ORD-10038",
    customerId: "cu5",
    customerName: "Emma Davis",
    customerEmail: "emma@example.com",
    status: "cancelled",
    paymentStatus: "refunded",
    items: [{ id: "oi5", productId: "p4", productName: "SEO Audit Checklist PDF", sku: "DL-SEO-001", quantity: 1, unitPrice: 19, totalPrice: 19 }],
    subtotal: 19,
    discount: 0,
    shipping: 0,
    tax: 1.71,
    total: 20.71,
    currencyCode: "USD",
    createdAt: "2026-05-22",
    updatedAt: "2026-05-23",
  },
  {
    id: "o6",
    orderNumber: "#ORD-10037",
    customerId: "cu6",
    customerName: "Marco Rossi",
    customerEmail: "marco@example.com",
    status: "delivered",
    paymentStatus: "paid",
    items: [{ id: "oi6", productId: "p6", productName: "1-on-1 Consulting Session", sku: "SVC-CONSULT-01", quantity: 1, unitPrice: 199, totalPrice: 199 }],
    subtotal: 199,
    discount: 20,
    shipping: 0,
    tax: 16.11,
    total: 195.11,
    currencyCode: "USD",
    createdAt: "2026-05-20",
    updatedAt: "2026-05-21",
    paidAt: "2026-05-20",
    deliveredAt: "2026-05-21",
  },
  {
    id: "o7",
    orderNumber: "#ORD-10036",
    customerId: "cu7",
    customerName: "Aisha Johnson",
    customerEmail: "aisha@example.com",
    status: "processing",
    paymentStatus: "paid",
    items: [{ id: "oi7", productId: "p7", productName: "ERVFlow Gift Card", sku: "GC-ERV-001", quantity: 3, unitPrice: 50, totalPrice: 150 }],
    subtotal: 150,
    discount: 0,
    shipping: 0,
    tax: 13.5,
    total: 163.5,
    currencyCode: "USD",
    createdAt: "2026-05-19",
    updatedAt: "2026-05-19",
    paidAt: "2026-05-19",
  },
  {
    id: "o8",
    orderNumber: "#ORD-10035",
    customerId: "cu1",
    customerName: "Sarah Mitchell",
    customerEmail: "sarah@example.com",
    status: "delivered",
    paymentStatus: "paid",
    items: [{ id: "oi8", productId: "p4", productName: "SEO Audit Checklist PDF", sku: "DL-SEO-001", quantity: 2, unitPrice: 19, totalPrice: 38 }],
    subtotal: 38,
    discount: 0,
    shipping: 0,
    tax: 3.42,
    total: 41.42,
    currencyCode: "USD",
    createdAt: "2026-05-15",
    updatedAt: "2026-05-15",
    paidAt: "2026-05-15",
    deliveredAt: "2026-05-15",
  },
];

// ─── Customers ────────────────────────────────────────────────────────────────

export const SAMPLE_CUSTOMERS: StoreCustomer[] = [
  {
    id: "cu1",
    name: "Sarah Mitchell",
    email: "sarah@example.com",
    phone: "+1 415 555 0101",
    status: "active",
    tags: ["vip", "newsletter"],
    totalOrders: 12,
    totalSpent: 847.32,
    averageOrderValue: 70.61,
    rewardPoints: 1240,
    storeCredit: 25.0,
    lastOrderDate: "2026-05-28",
    registeredAt: "2024-08-15",
    country: "US",
    isVip: true,
    segment: "vip",
  },
  {
    id: "cu2",
    name: "James Torres",
    email: "james@example.com",
    phone: "+1 213 555 0144",
    status: "active",
    tags: ["newsletter"],
    totalOrders: 5,
    totalSpent: 312.65,
    averageOrderValue: 62.53,
    rewardPoints: 620,
    storeCredit: 0,
    lastOrderDate: "2026-05-27",
    registeredAt: "2025-01-20",
    country: "US",
    segment: "regular",
  },
  {
    id: "cu3",
    name: "Priya Nair",
    email: "priya@example.com",
    phone: "+91 98765 43210",
    status: "active",
    tags: ["subscription"],
    totalOrders: 8,
    totalSpent: 1043.8,
    averageOrderValue: 130.48,
    rewardPoints: 2080,
    storeCredit: 50.0,
    lastOrderDate: "2026-05-26",
    registeredAt: "2024-06-10",
    country: "IN",
    isVip: true,
    segment: "vip",
  },
  {
    id: "cu4",
    name: "Liam Chen",
    email: "liam@example.com",
    phone: "+65 9123 4567",
    status: "active",
    tags: [],
    totalOrders: 1,
    totalSpent: 140.61,
    averageOrderValue: 140.61,
    rewardPoints: 140,
    storeCredit: 0,
    lastOrderDate: "2026-05-25",
    registeredAt: "2026-05-24",
    country: "SG",
    segment: "new",
  },
  {
    id: "cu5",
    name: "Emma Davis",
    email: "emma@example.com",
    phone: "+44 20 7946 0958",
    status: "active",
    tags: ["newsletter"],
    totalOrders: 3,
    totalSpent: 108.14,
    averageOrderValue: 36.05,
    rewardPoints: 80,
    storeCredit: 20.71,
    lastOrderDate: "2026-05-22",
    registeredAt: "2025-04-18",
    country: "GB",
    segment: "regular",
  },
  {
    id: "cu6",
    name: "Marco Rossi",
    email: "marco@example.com",
    phone: "+39 06 1234 5678",
    status: "active",
    tags: ["consulting"],
    totalOrders: 4,
    totalSpent: 628.44,
    averageOrderValue: 157.11,
    rewardPoints: 1260,
    storeCredit: 0,
    lastOrderDate: "2026-05-20",
    registeredAt: "2024-11-03",
    country: "IT",
    isVip: true,
    segment: "vip",
  },
  {
    id: "cu7",
    name: "Aisha Johnson",
    email: "aisha@example.com",
    phone: "+1 312 555 0187",
    status: "active",
    tags: ["gift"],
    totalOrders: 7,
    totalSpent: 490.5,
    averageOrderValue: 70.07,
    rewardPoints: 980,
    storeCredit: 10.0,
    lastOrderDate: "2026-05-19",
    registeredAt: "2024-10-22",
    country: "US",
    segment: "regular",
  },
  {
    id: "cu8",
    name: "David Park",
    email: "david@example.com",
    status: "active",
    tags: [],
    totalOrders: 0,
    totalSpent: 0,
    averageOrderValue: 0,
    rewardPoints: 50,
    storeCredit: 0,
    registeredAt: "2026-05-01",
    country: "KR",
    segment: "new",
  },
  {
    id: "cu9",
    name: "Sofia Mendez",
    email: "sofia@example.com",
    phone: "+34 91 123 4567",
    status: "active",
    tags: ["newsletter", "inactive"],
    totalOrders: 2,
    totalSpent: 68.0,
    averageOrderValue: 34.0,
    rewardPoints: 30,
    storeCredit: 0,
    lastOrderDate: "2025-11-14",
    registeredAt: "2025-09-08",
    country: "ES",
    segment: "at_risk",
  },
];

// ─── Categories ───────────────────────────────────────────────────────────────

export const SAMPLE_CATEGORIES: StoreCategory[] = [
  { id: "cat1", name: "Templates", slug: "templates", productCount: 18, status: "active", sortOrder: 1, createdAt: "2024-01-01", description: "Digital templates for designers and developers." },
  { id: "cat2", name: "Subscriptions", slug: "subscriptions", productCount: 4, status: "active", sortOrder: 2, createdAt: "2024-01-01", description: "Monthly and annual SaaS plans." },
  { id: "cat3", name: "Digital Downloads", slug: "digital-downloads", productCount: 32, status: "active", sortOrder: 3, createdAt: "2024-01-01", description: "Ebooks, PDFs, and downloadable assets." },
  { id: "cat4", name: "Merchandise", slug: "merchandise", productCount: 11, status: "active", sortOrder: 4, createdAt: "2024-03-15", description: "Branded apparel and physical goods." },
  { id: "cat5", name: "Services", slug: "services", productCount: 6, status: "active", sortOrder: 5, createdAt: "2024-03-15", description: "Consulting and expert services." },
];

// ─── Coupons ──────────────────────────────────────────────────────────────────

export const SAMPLE_COUPONS: StoreCoupon[] = [
  { id: "cp1", code: "WELCOME10", type: "percent", value: 10, usageLimit: 500, usageCount: 312, freeShipping: false, status: "active", createdAt: "2025-01-01", minimumSpend: 25, expiresAt: "2026-12-31" },
  { id: "cp2", code: "SUMMER25", type: "percent", value: 25, usageLimit: 200, usageCount: 156, freeShipping: false, status: "active", createdAt: "2026-05-01", expiresAt: "2026-07-31" },
  { id: "cp3", code: "FREESHIP", type: "fixed_cart", value: 0, usageLimit: 1000, usageCount: 489, freeShipping: true, status: "active", createdAt: "2025-06-01", minimumSpend: 50 },
  { id: "cp4", code: "FLAT20OFF", type: "fixed_cart", value: 20, usageLimit: 100, usageCount: 100, freeShipping: false, status: "expired", createdAt: "2025-12-01", expiresAt: "2026-01-31" },
  { id: "cp5", code: "VIP2026", type: "percent", value: 30, usageLimitPerUser: 1, usageCount: 23, freeShipping: true, status: "active", createdAt: "2026-01-01", expiresAt: "2026-12-31" },
];

// ─── Inventory ────────────────────────────────────────────────────────────────

export const SAMPLE_INVENTORY: InventoryItem[] = [
  { id: "inv1", productId: "p1", productName: "Premium SaaS Dashboard Template", sku: "TMPL-001", type: "digital", stock: 9999, lowStockThreshold: 0, stockStatus: "in_stock", backorderEnabled: false, lastUpdated: "2026-05-20", featuredImage: "https://placehold.co/40x40/d14c23/fff?text=DS" },
  { id: "inv2", productId: "p5", productName: "Pro T-Shirt (S)", sku: "MERCH-TS-S", type: "variable", stock: 14, lowStockThreshold: 20, stockStatus: "low_stock", backorderEnabled: false, lastUpdated: "2026-05-22", warehouseLocation: "A-12", featuredImage: "https://placehold.co/40x40/16a34a/fff?text=TS" },
  { id: "inv3", productId: "p5b", productName: "Pro T-Shirt (M)", sku: "MERCH-TS-M", type: "variable", stock: 0, lowStockThreshold: 20, stockStatus: "out_of_stock", backorderEnabled: true, lastUpdated: "2026-05-18", warehouseLocation: "A-12" },
  { id: "inv4", productId: "p5c", productName: "Pro T-Shirt (L)", sku: "MERCH-TS-L", type: "variable", stock: 42, lowStockThreshold: 10, stockStatus: "in_stock", backorderEnabled: false, lastUpdated: "2026-05-22", warehouseLocation: "A-13" },
  { id: "inv5", productId: "p4", productName: "SEO Audit Checklist PDF", sku: "DL-SEO-001", type: "downloadable", stock: 9999, lowStockThreshold: 0, stockStatus: "in_stock", backorderEnabled: false, lastUpdated: "2026-02-14" },
];

// ─── Automations ─────────────────────────────────────────────────────────────

export const SAMPLE_AUTOMATIONS: AutomationRule[] = [
  {
    id: "auto1",
    name: "Welcome Email on Registration",
    description: "Send a welcome email when a new customer registers.",
    trigger: "customer_registered",
    conditions: [],
    actions: [{ type: "send_email", config: { template: "welcome_email", subject: "Welcome to ERVFlow!" } }],
    status: "active",
    runCount: 892,
    lastRunAt: "2026-06-04T18:22:00Z",
    isBuiltIn: true,
    createdAt: "2024-01-01",
  },
  {
    id: "auto2",
    name: "Abandoned Cart Recovery",
    description: "Send a recovery email 1 hour after cart abandonment.",
    trigger: "abandoned_cart",
    conditions: [{ field: "cart_value", operator: "greater_than", value: 30 }],
    actions: [{ type: "send_email", config: { template: "abandoned_cart", delay_hours: 1 } }],
    status: "active",
    runCount: 1234,
    lastRunAt: "2026-06-05T08:10:00Z",
    isBuiltIn: true,
    createdAt: "2024-01-01",
  },
  {
    id: "auto3",
    name: "Low Stock Admin Alert",
    description: "Notify admin when product stock falls below threshold.",
    trigger: "product_low_stock",
    conditions: [],
    actions: [{ type: "notify_admin", config: { channel: "email" } }],
    status: "active",
    runCount: 47,
    lastRunAt: "2026-06-04T12:00:00Z",
    isBuiltIn: true,
    createdAt: "2024-01-01",
  },
  {
    id: "auto4",
    name: "First Purchase Reward Points",
    description: "Award 500 bonus points on a customer's first purchase.",
    trigger: "customer_first_purchase",
    conditions: [],
    actions: [
      { type: "add_reward_points", config: { points: 500, reason: "First purchase bonus" } },
      { type: "send_email", config: { template: "first_purchase_reward" } },
    ],
    status: "active",
    runCount: 318,
    lastRunAt: "2026-06-05T07:44:00Z",
    isBuiltIn: true,
    createdAt: "2024-01-01",
  },
  {
    id: "auto5",
    name: "Review Request After Delivery",
    description: "Ask customers for a review 3 days after delivery.",
    trigger: "order_delivered",
    conditions: [],
    actions: [{ type: "send_email", config: { template: "review_request", delay_days: 3 } }],
    status: "paused",
    runCount: 0,
    createdAt: "2026-04-01",
  },
  {
    id: "auto6",
    name: "VIP Customer Store Credit",
    description: "Award $50 store credit when a customer spends over $500.",
    trigger: "customer_first_purchase",
    conditions: [{ field: "total_spent", operator: "greater_than", value: 500 }],
    actions: [{ type: "add_store_credit", config: { amount: 50, reason: "VIP milestone reward" } }],
    status: "active",
    runCount: 12,
    lastRunAt: "2026-05-28T15:30:00Z",
    createdAt: "2025-03-01",
  },
];

// ─── Rewards ──────────────────────────────────────────────────────────────────

export const SAMPLE_REWARDS: CustomerReward[] = [
  { customerId: "cu1", customerName: "Sarah Mitchell", customerEmail: "sarah@example.com", points: 1240, tier: "gold", pointsToNextTier: 1760, lastEarnedAt: "2026-05-28" },
  { customerId: "cu3", customerName: "Priya Nair", customerEmail: "priya@example.com", points: 2080, tier: "platinum", pointsToNextTier: 0, lastEarnedAt: "2026-05-26" },
  { customerId: "cu6", customerName: "Marco Rossi", customerEmail: "marco@example.com", points: 1260, tier: "gold", pointsToNextTier: 1740, lastEarnedAt: "2026-05-20" },
  { customerId: "cu2", customerName: "James Torres", customerEmail: "james@example.com", points: 620, tier: "silver", pointsToNextTier: 380, lastEarnedAt: "2026-05-27" },
  { customerId: "cu7", customerName: "Aisha Johnson", customerEmail: "aisha@example.com", points: 980, tier: "silver", pointsToNextTier: 20, lastEarnedAt: "2026-05-19" },
];

// ─── Credits ──────────────────────────────────────────────────────────────────

export const SAMPLE_CREDITS: CustomerCredit[] = [
  { customerId: "cu1", customerName: "Sarah Mitchell", customerEmail: "sarah@example.com", balance: 25.0, lastTransactionAt: "2026-05-20", transactions: [] },
  { customerId: "cu3", customerName: "Priya Nair", customerEmail: "priya@example.com", balance: 50.0, lastTransactionAt: "2026-04-10", transactions: [] },
  { customerId: "cu5", customerName: "Emma Davis", customerEmail: "emma@example.com", balance: 20.71, lastTransactionAt: "2026-05-23", transactions: [] },
  { customerId: "cu7", customerName: "Aisha Johnson", customerEmail: "aisha@example.com", balance: 10.0, lastTransactionAt: "2026-03-15", transactions: [] },
];
