import type { Email, MailLabel } from "./mail.types";

export const LABELS: MailLabel[] = [
  { id: "work", name: "Works", color: "bg-blue-500" },
  { id: "private", name: "Private", color: "bg-emerald-500" },
  { id: "important", name: "Important", color: "bg-rose-500" },
];

export const INITIAL_EMAILS: Email[] = [
  // ── Inbox ──────────────────────────────────────────────────────
  {
    id: "e1",
    from: { name: "Sarah Mitchell", email: "sarah.mitchell@acmecorp.com" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "Q3 Marketing Campaign Review",
    preview: "Hi, I've attached the full performance report for our Q3 campaign. Key metrics are up 18% compared to last quarter...",
    body: `Hi,\n\nI've attached the full performance report for our Q3 campaign. Key metrics are up 18% compared to last quarter — especially organic traffic which hit an all-time high of 84k monthly sessions.\n\nA few highlights:\n• Email open rate: 34.2% (industry avg: 21%)\n• Conversion rate: 4.1% from landing pages\n• Paid CPC dropped from $3.40 to $1.90\n\nLet me know when you'd like to review this in detail.\n\nBest,\nSarah`,
    date: "2026-06-04T09:14:00Z",
    read: false,
    starred: true,
    folder: "inbox",
    labels: ["work"],
    attachments: [{ name: "Q3_Campaign_Report.pdf", size: "2.4 MB", type: "pdf" }],
  },
  {
    id: "e2",
    from: { name: "Ravi Gupta", email: "ravi@vyntra.com" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "Platform Update — v3.4.2 Release Notes",
    preview: "We've deployed a new release with several improvements including the Lighthouse Keeper module, improved CRM filters...",
    body: `Hello,\n\nWe're excited to announce the release of Vyntra v3.4.2. Here's what's new:\n\n🚀 New Features\n• Lighthouse Keeper — full performance audit module\n• SEO Tools — semantic keyword explorer & SERP simulator\n• Gallery Hub — media management with cover assignment\n• Mail module — full inbox management experience\n\n🐛 Bug Fixes\n• Fixed primary color not reflecting across the app\n• Resolved sidebar blink on page reload\n• CRM contact drawer React Select improvements\n\nThank you for being a valued customer.\n\nBest,\nRavi Gupta\nVyntra Platform`,
    date: "2026-06-04T08:00:00Z",
    read: false,
    starred: false,
    folder: "inbox",
    labels: ["important"],
  },
  {
    id: "e3",
    from: { name: "Alex Thompson", email: "alex.t@bloomstudio.io" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "Partnership Proposal — Co-marketing Opportunity",
    preview: "Following our call last Thursday, I've put together a proposal that outlines what a content syndication partnership...",
    body: `Hi,\n\nFollowing our call last Thursday, I've put together a proposal that outlines what a content syndication partnership could look like between Bloom Studio and Acme Corp.\n\nThe main idea is to co-publish bi-weekly design case studies that reach both our audiences — estimated combined reach of ~120k engaged readers.\n\nI've included:\n• Revenue share model\n• Content calendar template\n• KPI targets for 90 days\n\nLooking forward to your thoughts.\n\nAlex`,
    date: "2026-06-03T16:45:00Z",
    read: true,
    starred: false,
    folder: "inbox",
    labels: ["work"],
    attachments: [{ name: "Partnership_Proposal.docx", size: "890 KB", type: "doc" }],
  },
  {
    id: "e4",
    from: { name: "Stripe", email: "receipts@stripe.com" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "Your invoice from Stripe — June 2026",
    preview: "Invoice #INV-2026-0611 for $490.00 has been generated for your subscription. Payment will be automatically collected...",
    body: `Invoice #INV-2026-0611\n\nDate: June 4, 2026\nAmount: $490.00\nPlan: Vyntra Pro (Annual)\n\nThis invoice has been paid successfully from your card ending in 4242.\n\nThank you for your business.`,
    date: "2026-06-04T00:01:00Z",
    read: true,
    starred: false,
    folder: "inbox",
    labels: [],
  },
  {
    id: "e5",
    from: { name: "Emma Davis", email: "emma.davis@acmecorp.com" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "Design System Tokens — Final Review",
    preview: "The new token file is ready for your sign-off. I've restructured the colour system around semantic HSL variables...",
    body: `Hi,\n\nThe updated design token file is ready for your final review. Key changes:\n\n• Migrated all colours to HSL space-separated format\n• Added semantic aliases (--primary, --secondary, --accent)\n• Dark mode values now live in the same token\n\nI'll push to the design system repo once you approve.\n\nBest,\nEmma`,
    date: "2026-06-02T11:30:00Z",
    read: false,
    starred: true,
    folder: "inbox",
    labels: ["work", "important"],
    attachments: [
      { name: "tokens.json", size: "14 KB", type: "json" },
      { name: "tokens_preview.png", size: "340 KB", type: "img" },
    ],
  },
  {
    id: "e6",
    from: { name: "GitHub", email: "noreply@github.com" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "[vyntra/web] PR #47 merged — Lighthouse module",
    preview: "Pull request #47 'feat: add Lighthouse Keeper performance module' was merged into main by ravigupta.",
    body: `Pull request #47 was merged into main.\n\nTitle: feat: add Lighthouse Keeper performance module\nAuthor: ravigupta\nMerged by: ravigupta\n\nFiles changed: 8\nCommits: 3\n\nView on GitHub →`,
    date: "2026-06-01T14:22:00Z",
    read: true,
    starred: false,
    folder: "inbox",
    labels: [],
  },

  // ── Sent ───────────────────────────────────────────────────────
  {
    id: "e7",
    from: { name: "Me", email: "admin@acme.com" },
    to: [{ name: "Sarah Mitchell", email: "sarah.mitchell@acmecorp.com" }],
    subject: "Re: Q3 Marketing Campaign Review",
    preview: "Thanks Sarah, the numbers look great! Let's schedule a call for Thursday to go through the highlights...",
    body: `Hi Sarah,\n\nThanks — the numbers look great! 18% growth is well above our target.\n\nLet's schedule a call for Thursday to go through the highlights with the broader team. I'll send a calendar invite.\n\nBest,\nAdmin`,
    date: "2026-06-04T10:05:00Z",
    read: true,
    starred: false,
    folder: "sent",
    labels: ["work"],
  },
  {
    id: "e8",
    from: { name: "Me", email: "admin@acme.com" },
    to: [{ name: "Alex Thompson", email: "alex.t@bloomstudio.io" }],
    subject: "Re: Partnership Proposal",
    preview: "Hi Alex, I've reviewed the proposal with our team. We're interested in moving forward, particularly around the...",
    body: `Hi Alex,\n\nI've reviewed the proposal with our team and we're genuinely interested in moving forward — particularly around the design case studies format.\n\nCan we get on a 30-minute call next week to align on the first piece?\n\nBest,\nAdmin`,
    date: "2026-06-03T18:00:00Z",
    read: true,
    starred: false,
    folder: "sent",
    labels: ["work"],
  },
  {
    id: "e9",
    from: { name: "Me", email: "admin@acme.com" },
    to: [{ name: "Emma Davis", email: "emma.davis@acmecorp.com" }],
    subject: "Re: Design System Tokens",
    preview: "Looks great Emma. One minor note — can we add a --warning token to the palette? Otherwise, approved!",
    body: `Hi Emma,\n\nThis looks excellent. One minor note: can we add a --warning token to match the amber-500 we're using for draft states? Otherwise it's approved — go ahead and push.\n\nThanks,\nAdmin`,
    date: "2026-06-02T14:15:00Z",
    read: true,
    starred: false,
    folder: "sent",
    labels: ["work"],
  },

  // ── Drafts ─────────────────────────────────────────────────────
  {
    id: "e10",
    from: { name: "Me", email: "admin@acme.com" },
    to: [{ name: "Vasudev Sharma", email: "vasu14082@gmail.com" }],
    subject: "Onboarding Plan — New Team Member",
    preview: "Hi Vasudev, welcome to the team! I wanted to share the onboarding plan for your first two weeks...",
    body: `Hi Vasudev,\n\nWelcome to the team! I wanted to share the onboarding plan for your first two weeks:\n\nWeek 1:\n• Product walkthrough with Sarah\n• Code review session with Emma\n\nWeek 2:\n• First feature ownership\n\n[Draft — not sent]`,
    date: "2026-06-03T15:00:00Z",
    read: true,
    starred: false,
    folder: "drafts",
    labels: [],
  },
  {
    id: "e11",
    from: { name: "Me", email: "admin@acme.com" },
    to: [],
    subject: "Blog Post: Why Design Tokens Matter",
    preview: "Design tokens are the atomic building blocks of a scalable design system. When implemented correctly...",
    body: `Design tokens are the atomic building blocks of a scalable design system. When implemented correctly, they allow teams to change the entire look of a product by updating a single source of truth.\n\n[Draft — incomplete]`,
    date: "2026-06-01T09:00:00Z",
    read: true,
    starred: false,
    folder: "drafts",
    labels: ["private"],
  },

  // ── Deleted ────────────────────────────────────────────────────
  {
    id: "e12",
    from: { name: "Newsletter Bot", email: "news@techdigest.io" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "Tech Digest Weekly — Issue #112",
    preview: "This week in tech: AI takes over developer workflows, new CSS features in Chrome 127, and the state of...",
    body: `Tech Digest — Issue #112\n\nTop stories this week:\n• AI takes over developer workflows\n• New CSS features in Chrome 127\n• The state of TypeScript in 2026`,
    date: "2026-05-30T07:00:00Z",
    read: true,
    starred: false,
    folder: "deleted",
    labels: [],
  },
  {
    id: "e13",
    from: { name: "Promo Bot", email: "deals@saastools.com" },
    to: [{ name: "Me", email: "admin@acme.com" }],
    subject: "🔥 50% off all annual plans — Today only",
    preview: "Don't miss our biggest sale of the year. Upgrade to any annual plan and save 50%...",
    body: `Don't miss our biggest sale of the year.\n\nUpgrade to any annual plan and save 50% — today only.\n\nShop now →`,
    date: "2026-05-28T10:00:00Z",
    read: true,
    starred: false,
    folder: "deleted",
    labels: [],
  },
];

export const FOLDER_LABELS: Record<string, string> = {
  inbox: "Inbox",
  sent: "Sent",
  drafts: "Drafts",
  starred: "Starred",
  deleted: "Deleted",
};
